//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid ID { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string BrandCode { get; set; }
        public string Segmento { get; set; }
        public string Category { get; set; }
    }
}
